name: fenicsx-env
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python>=3.13

  # FEniCSx / DOLFINx and math ecosystem
  - fenics-dolfinx
  - fenics-ufl
  - mpi4py
  - numpy
  - petsc4py

  # Meshing tools
  - gmsh
  - python-gmsh
  - meshio

  # Visualization
  - pyvista
