[project]
name = "fenicsx-potential-flow-2d"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vitomurgida" }
]
requires-python = ">=3.13"
dependencies = [
    "meshio>=5.3.5",
    "numpy>=2.5.1",
    "pathlib>=1.0.1",
    "pyvista>=0.48.4",
]

[project.scripts]
fenicsx-potential-flow-2d = "fenicsx_potential_flow_2d:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
